### ISSUE TITLE
Leak Detection - Historical Leak - Workflow

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Leak_Detection_Issues#95]
Currently, if a user identifies a historical leak, the leak information is shown as editable, and report is not visible.  Please make it so that historical leaks cannot be edited, have photos attached, be deleted or be emailed.  Please do make reports available.

**Comment by kanglu666** [comment]
done, identify historical leaks on the map, pick one from the result list, the historical leak report will be automatically open. Since the scheme of the old leak is not the same as the new leak schema, and the historical leak is not editable, so system will not navigate to the leak detail page for historical leak.

Please Clear Browser cache, test.
i'm working on discrepancy tool for leak mobile. it will be available very soon.

**Comment by alanfoster99** [comment]
Historical report is not linking -- please recheck.

**Comment by kanglu666** [comment]
working fine for me. you need tap on the arrow icon, then it will fire the report.

**Comment by alanfoster99** [comment]
Works -- popups were blocked.  Closing.
